<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.gitee.pkmer</groupId>
        <artifactId>app-points</artifactId>
        <version>2.2.6</version>
    </parent>

    <artifactId>points-domain</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!--   自身依赖 start    -->
        <dependency>
            <groupId>io.gitee.pkmer</groupId>
            <artifactId>points-types</artifactId>
            <version>2.2.6</version>
        </dependency>
        <dependency>
            <groupId>io.gitee.pkmer</groupId>
            <artifactId>pkmer-boot-convention</artifactId>
        </dependency>
        <dependency>
            <groupId>io.gitee.pkmer</groupId>
            <artifactId>pkmer-boot-ddd</artifactId>
        </dependency>
        <dependency>
            <groupId>io.gitee.pkmer</groupId>
            <artifactId>pkmer-boot-starter-rabbitmq</artifactId>
        </dependency>
        <dependency>
            <groupId>io.gitee.pkmer</groupId>
            <artifactId>pkmer-boot-starter-cache</artifactId>
        </dependency>
        <!--   自身依赖 end    -->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-core</artifactId>
        </dependency>
    </dependencies>

</project>