package org.hzz.course.infrastructure.dao.model;

import java.util.Date;

/**
 * generated by MyBatis Generator.
 * course(草稿课程) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2024/06/26
 */
public class Course {
    // course.id (课程草稿id，对应正式草稿id)
    private Long id;

    // course.name (课程名称)
    private String name;

    // course.course_type (课程类型，1：直播课，2：录播课)
    private Byte courseType;

    // course.cover_url (封面链接)
    private String coverUrl;

    // course.first_cate_id (一级课程分类id)
    private Long firstCateId;

    // course.second_cate_id (二级课程分类id)
    private Long secondCateId;

    // course.third_cate_id (三级课程分类id)
    private Long thirdCateId;

    // course.free (售卖方式0付费，1：免费)
    private Byte free;

    // course.price (课程价格，单位为分)
    private Integer price;

    // course.template_type (模板类型，1：固定模板，2：自定义模板)
    private Byte templateType;

    // course.template_url (自定义模板的连接)
    private String templateUrl;

    // course.status (课程状态，1：待上架，2：已上架，3：下架，4：已完结)
    private Byte status;

    // course.purchase_start_time (课程购买有效期开始时间)
    private Date purchaseStartTime;

    // course.purchase_end_time (课程购买有效期结束时间)
    private Date purchaseEndTime;

    // course.step (信息填写进度)
    private Byte step;

    // course.score (课程评价得分，45代表4.5星)
    private Integer score;

    // course.media_duration (课程总时长)
    private Integer mediaDuration;

    // course.valid_duration (课程有效期，单位月)
    private Integer validDuration;

    // course.section_num (课程总节数，包括练习)
    private Integer sectionNum;

    // course.dep_id (部门id)
    private Long depId;

    // course.publish_times (发布次数)
    private Integer publishTimes;

    // course.publish_time (最近一次发布时间)
    private Date publishTime;

    // course.create_time (创建时间)
    private Date createTime;

    // course.update_time (更新时间)
    private Date updateTime;

    // course.creater_id (创建人Id)
    private Long createrId;

    // course.updater_id (更新人Id)
    private Long updaterId;

    // course.deleted (逻辑删除)
    private Byte deleted;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Byte getCourseType() {
        return courseType;
    }

    public void setCourseType(Byte courseType) {
        this.courseType = courseType;
    }

    public String getCoverUrl() {
        return coverUrl;
    }

    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }

    public Long getFirstCateId() {
        return firstCateId;
    }

    public void setFirstCateId(Long firstCateId) {
        this.firstCateId = firstCateId;
    }

    public Long getSecondCateId() {
        return secondCateId;
    }

    public void setSecondCateId(Long secondCateId) {
        this.secondCateId = secondCateId;
    }

    public Long getThirdCateId() {
        return thirdCateId;
    }

    public void setThirdCateId(Long thirdCateId) {
        this.thirdCateId = thirdCateId;
    }

    public Byte getFree() {
        return free;
    }

    public void setFree(Byte free) {
        this.free = free;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public Byte getTemplateType() {
        return templateType;
    }

    public void setTemplateType(Byte templateType) {
        this.templateType = templateType;
    }

    public String getTemplateUrl() {
        return templateUrl;
    }

    public void setTemplateUrl(String templateUrl) {
        this.templateUrl = templateUrl;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Date getPurchaseStartTime() {
        return purchaseStartTime;
    }

    public void setPurchaseStartTime(Date purchaseStartTime) {
        this.purchaseStartTime = purchaseStartTime;
    }

    public Date getPurchaseEndTime() {
        return purchaseEndTime;
    }

    public void setPurchaseEndTime(Date purchaseEndTime) {
        this.purchaseEndTime = purchaseEndTime;
    }

    public Byte getStep() {
        return step;
    }

    public void setStep(Byte step) {
        this.step = step;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Integer getMediaDuration() {
        return mediaDuration;
    }

    public void setMediaDuration(Integer mediaDuration) {
        this.mediaDuration = mediaDuration;
    }

    public Integer getValidDuration() {
        return validDuration;
    }

    public void setValidDuration(Integer validDuration) {
        this.validDuration = validDuration;
    }

    public Integer getSectionNum() {
        return sectionNum;
    }

    public void setSectionNum(Integer sectionNum) {
        this.sectionNum = sectionNum;
    }

    public Long getDepId() {
        return depId;
    }

    public void setDepId(Long depId) {
        this.depId = depId;
    }

    public Integer getPublishTimes() {
        return publishTimes;
    }

    public void setPublishTimes(Integer publishTimes) {
        this.publishTimes = publishTimes;
    }

    public Date getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Long getCreaterId() {
        return createrId;
    }

    public void setCreaterId(Long createrId) {
        this.createrId = createrId;
    }

    public Long getUpdaterId() {
        return updaterId;
    }

    public void setUpdaterId(Long updaterId) {
        this.updaterId = updaterId;
    }

    public Byte getDeleted() {
        return deleted;
    }

    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }
}