<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.gitee.pkmer</groupId>
        <artifactId>app-learning</artifactId>
        <version>2.2.7-SNAPSHOT</version>
    </parent>

    <artifactId>learning-domain</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!--  引入自身依赖start      -->
        <dependency>
            <groupId>io.gitee.pkmer</groupId>
            <artifactId>learning-types</artifactId>
            <version>2.2.7-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.gitee.pkmer</groupId>
            <artifactId>course-cache</artifactId>
            <version>2.2.7-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.gitee.pkmer</groupId>
            <artifactId>pkmer-boot-convention</artifactId>
        </dependency>
        <dependency>
            <groupId>io.gitee.pkmer</groupId>
            <artifactId>pkmer-boot-common</artifactId>
        </dependency>
        <dependency>
            <groupId>io.gitee.pkmer</groupId>
            <artifactId>pkmer-boot-ddd</artifactId>
        </dependency>
        <dependency>
            <groupId>io.gitee.pkmer</groupId>
            <artifactId>remark-types</artifactId>
            <version>2.2.7-SNAPSHOT</version>
        </dependency>
        <!--  引入自身依赖end      -->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-core</artifactId>
        </dependency>
    </dependencies>
</project>