package org.hzz.points.infrastructure.dao.model.points;

import org.hzz.mybatis.annotation.SnowflakeId;

/**
 * generated by MyBatis Generator.
 * points_board(学霸天梯榜) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2024/07/31
 */
public class PointsBoard {
    // 榜单id
    @SnowflakeId
    private Long id;

    // 学生id
    private Long userId;

    // 积分值
    private Integer points;

    // 名次，只记录赛季前100
    private Byte rank;

    // 赛季id
    private Short season;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getPoints() {
        return points;
    }

    public void setPoints(Integer points) {
        this.points = points;
    }

    public Byte getRank() {
        return rank;
    }

    public void setRank(Byte rank) {
        this.rank = rank;
    }

    public Short getSeason() {
        return season;
    }

    public void setSeason(Short season) {
        this.season = season;
    }
}