package org.hzz.points.infrastructure.dao.model.points;

import org.hzz.mybatis.annotation.SnowflakeId;
import org.hzz.points.types.enums.PointsType;

import java.time.LocalDateTime;

/**
 * generated by MyBatis Generator.
 * points_record(学习积分记录，每个月底清零) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2024/07/29
 */
public class PointsRecord {
    // 积分记录表id
    @SnowflakeId
    private Long id;

    // 用户id
    private Long userId;

    // 积分方式：1-课程学习，2-每日签到，3-课程问答， 4-课程笔记，5-课程评价
    private PointsType type;

    // 积分值
    private Byte points;

    // 创建时间
    private LocalDateTime createTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public PointsType getType() {
        return type;
    }

    public void setType(PointsType type) {
        this.type = type;
    }

    public Byte getPoints() {
        return points;
    }

    public void setPoints(Byte points) {
        this.points = points;
    }

    public LocalDateTime getCreateTime() {
        return createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }
}