package org.hzz.points.infrastructure.dao.model.points;

import java.time.LocalDate;

/**
 * generated by MyBatis Generator.
 * points_board_season(赛季表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2024/07/31
 */
public class PointsBoardSeason {
    // 自增长id，season标示
    private Integer id;

    // 赛季名称，例如：第1赛季
    private String name;

    // 赛季开始时间
    private LocalDate beginTime;

    // 赛季结束时间
    private LocalDate endTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(LocalDate beginTime) {
        this.beginTime = beginTime;
    }

    public LocalDate getEndTime() {
        return endTime;
    }

    public void setEndTime(LocalDate endTime) {
        this.endTime = endTime;
    }
}