DROP TABLE IF EXISTS `course`;
CREATE TABLE `course`  (
   `id` bigint NOT NULL COMMENT '课程草稿id，对应正式草稿id',
   `name` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '课程名称',
   `course_type` tinyint NOT NULL DEFAULT 2 COMMENT '课程类型，1：直播课，2：录播课',
   `cover_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '封面链接',
   `first_cate_id` bigint NOT NULL COMMENT '一级课程分类id',
   `second_cate_id` bigint NOT NULL DEFAULT 0 COMMENT '二级课程分类id',
   `third_cate_id` bigint NOT NULL DEFAULT 0 COMMENT '三级课程分类id',
   `free` tinyint NOT NULL DEFAULT 0 COMMENT '售卖方式0付费，1：免费',
   `price` int NOT NULL COMMENT '课程价格，单位为分',
   `template_type` tinyint NOT NULL DEFAULT 1 COMMENT '模板类型，1：固定模板，2：自定义模板',
   `template_url` varchar(255) NOT NULL DEFAULT '' COMMENT '自定义模板的连接',
   `status` tinyint NOT NULL COMMENT '课程状态，1：待上架，2：已上架，3：下架，4：已完结',
   `purchase_start_time` datetime NULL DEFAULT NULL COMMENT '课程购买有效期开始时间',
   `purchase_end_time` datetime NOT NULL COMMENT '课程购买有效期结束时间',
   `step` tinyint NOT NULL COMMENT '信息填写进度',
   `score` int NULL DEFAULT 0 COMMENT '课程评价得分，45代表4.5星',
   `media_duration` int(10) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT '课程总时长',
   `valid_duration` int NOT NULL COMMENT '课程有效期，单位月',
   `section_num` int NULL DEFAULT NULL COMMENT '课程总节数，包括练习',
   `dep_id` bigint NOT NULL COMMENT '部门id',
   `publish_times` int NULL DEFAULT 1 COMMENT '发布次数',
   `publish_time` datetime NULL DEFAULT NULL COMMENT '最近一次发布时间',
   `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   `creater_id` bigint NOT NULL COMMENT '创建人Id',
   `updater_id` bigint NOT NULL COMMENT '更新人Id',
   `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除',
   PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '草稿课程' ROW_FORMAT = Dynamic;
