DROP TABLE IF EXISTS `course_draft`;
CREATE TABLE `course_draft`  (
     `id` bigint NOT NULL COMMENT '课程草稿id，对应正式草稿id',
     `name` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '课程名称',
     `course_type` tinyint NOT NULL DEFAULT 2 COMMENT '课程类型，1：直播课，2：录播课',
     `cover_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '封面链接',
     `first_cate_id` bigint NOT NULL COMMENT '一级课程分类id',
     `second_cate_id` bigint NOT NULL DEFAULT 0 COMMENT '二级课程分类id',
     `third_cate_id` bigint NOT NULL DEFAULT 0 COMMENT '三级课程分类id',
     `free` tinyint NOT NULL DEFAULT 0 COMMENT '售卖方式0付费，1：免费',
     `price` int NOT NULL COMMENT '课程价格，单位为分',
     `template_type` tinyint NOT NULL DEFAULT 1 COMMENT '模板类型，1：固定模板，2：自定义模板',
     `template_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '自定义模板的连接',
     `status` tinyint NOT NULL DEFAULT 0 COMMENT '课程状态，0：待上架，1：已上架，2：下架，3：已完结',
     `purchase_start_time` datetime NULL DEFAULT NULL COMMENT '课程购买有效期开始时间',
     `purchase_end_time` datetime NOT NULL COMMENT '课程购买有效期结束时间',
     `step` tinyint NOT NULL COMMENT '信息填写进度1：基本信息已经保存，2：课程目录已经保存，3：课程视频已保存，4：课程题目已保存，5：课程老师已经保存',
     `score` int NULL DEFAULT 0 COMMENT '课程评价得分，45代表4.5星',
     `media_duration` int NOT NULL DEFAULT 0 COMMENT '视频总时长',
     `valid_duration` int NOT NULL DEFAULT 0 COMMENT '课程有效期，单位月',
     `section_num` int NOT NULL DEFAULT 0 COMMENT '课程总节数',
     `can_update` tinyint NOT NULL DEFAULT 1 COMMENT '是否可以更新',
     `dep_id` bigint NOT NULL DEFAULT 0 COMMENT '部门id',
     `publish_time` datetime NULL DEFAULT NULL COMMENT '最近一次发布时间',
     `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
     `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
     `creater_id` bigint NOT NULL DEFAULT 0 COMMENT '创建人ID',
     `updater_id` bigint NOT NULL DEFAULT 0 COMMENT '更新人ID',
     `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除',
     `c_version` int NULL DEFAULT 1,
     PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '草稿课程' ROW_FORMAT = Dynamic;
