package org.hzz.user.infrastructure.dao.entity.details;

import java.time.LocalDate;
import java.time.LocalDateTime;
import org.hzz.user.types.enums.Gender;

/**
 * generated by MyBatis Generator.
 * user_detail(教师详情表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2024/07/12
 */
public class UserDetail {
    // 关联用户id
    private Long id;

    // 用户类型：1-员工, 2-普通学员，3-老师
    private Byte type;

    // 名字
    private String name;

    // 性别：0-男性，1-女性
    private Gender gender;

    // 头像地址
    private String icon;

    // 邮箱
    private String email;

    // QQ号码
    private String qq;

    // 生日
    private LocalDate birthday;

    // 岗位
    private String job;

    // 省
    private String province;

    // 市
    private String city;

    // 区
    private String district;

    // 个人介绍
    private String intro;

    // 形象照地址
    private String photo;

    // 角色id
    private Long roleId;

    // 购买课程数量，学生才有该字段信息
    private Short courseAmount;

    // 创建时间
    private LocalDateTime createTime;

    // 更新时间
    private LocalDateTime updateTime;

    // 创建者id
    private Long creater;

    // 更新者id
    private Long updater;

    // 部门id
    private Long depId;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getQq() {
        return qq;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }

    public LocalDate getBirthday() {
        return birthday;
    }

    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }

    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public Short getCourseAmount() {
        return courseAmount;
    }

    public void setCourseAmount(Short courseAmount) {
        this.courseAmount = courseAmount;
    }

    public LocalDateTime getCreateTime() {
        return createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public Long getCreater() {
        return creater;
    }

    public void setCreater(Long creater) {
        this.creater = creater;
    }

    public Long getUpdater() {
        return updater;
    }

    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    public Long getDepId() {
        return depId;
    }

    public void setDepId(Long depId) {
        this.depId = depId;
    }
}