package org.hzz.domain.entity;

import java.util.Date;

/**
 * generated by MyBatis Generator.
 * app_user(用户表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2024/06/13
 */
public class AppUser {
    // app_user.id (主键)
    private Long id;

    // app_user.username (用户名)
    private String username;

    // app_user.password (密码)
    private String password;

    // app_user.email (邮箱)
    private String email;

    // app_user.cell_phone (手机号)
    private String cellPhone;

    // app_user.type (用户类型：1-员工, 2-普通学员，3-老师)
    private Byte type;

    // app_user.create_time (创建时间)
    private Date createTime;

    // app_user.update_time (创建时间)
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getCellPhone() {
        return cellPhone;
    }

    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}