package org.hzz.learning.infrastructure.dao.entity.record;

import java.time.LocalDateTime;

/**
 * generated by MyBatis Generator.
 * learning_record(学习记录表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2024/06/29
 */
public class LearningRecord {
    // 学习记录的id
    private Long id;

    // 对应课表的id
    private Long lessonId;

    // 对应小节的id
    private Long sectionId;

    // 用户id
    private Long userId;

    // 视频的当前观看时间点，单位秒
    private Integer moment;

    // 是否完成学习，默认false
    private Boolean finished;

    // 第一次观看时间
    private LocalDateTime createTime;

    // 完成学习的时间
    private LocalDateTime finishTime;

    // 更新时间（最近一次观看时间）
    private LocalDateTime updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getLessonId() {
        return lessonId;
    }

    public void setLessonId(Long lessonId) {
        this.lessonId = lessonId;
    }

    public Long getSectionId() {
        return sectionId;
    }

    public void setSectionId(Long sectionId) {
        this.sectionId = sectionId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getMoment() {
        return moment;
    }

    public void setMoment(Integer moment) {
        this.moment = moment;
    }

    public Boolean getFinished() {
        return finished;
    }

    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    public LocalDateTime getCreateTime() {
        return createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getFinishTime() {
        return finishTime;
    }

    public void setFinishTime(LocalDateTime finishTime) {
        this.finishTime = finishTime;
    }

    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }
}