package org.hzz.learning.infrastructure.dao.entity.record;

import java.util.Date;

/**
 * generated by MyBatis Generator.
 * learning_record(学习记录表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2024/06/28
 */
public class LearningRecord {
    // learning_record.id (学习记录的id)
    private Long id;

    // learning_record.lesson_id (对应课表的id)
    private Long lessonId;

    // learning_record.section_id (对应小节的id)
    private Long sectionId;

    // learning_record.user_id (用户id)
    private Long userId;

    // learning_record.moment (视频的当前观看时间点，单位秒)
    private Integer moment;

    // learning_record.finished (是否完成学习，默认false)
    private Boolean finished;

    // learning_record.create_time (第一次观看时间)
    private Date createTime;

    // learning_record.finish_time (完成学习的时间)
    private Date finishTime;

    // learning_record.update_time (更新时间（最近一次观看时间）)
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getLessonId() {
        return lessonId;
    }

    public void setLessonId(Long lessonId) {
        this.lessonId = lessonId;
    }

    public Long getSectionId() {
        return sectionId;
    }

    public void setSectionId(Long sectionId) {
        this.sectionId = sectionId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Integer getMoment() {
        return moment;
    }

    public void setMoment(Integer moment) {
        this.moment = moment;
    }

    public Boolean getFinished() {
        return finished;
    }

    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getFinishTime() {
        return finishTime;
    }

    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}