server:
  port: 8080
spring:
  #redis配置,注意因为我引入了docker会导致data-redis自动配置类PropertiesRedisConnectionDetails失效
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      #读超时
      timeout: 3000
      # 连接超时
      connect-timeout: 5000
      #lettuce连接池
      lettuce:
        pool:
          # 最小空闲连接
          min-idle: 5
          # 最大空闲连接
          max-idle: 10
          # 最大连接数
          max-active: 100
          # 连接分配应该阻塞的最大时间
          max-wait: 2000
  #docker配置（目前已经去掉，使得redis生效）
#  docker:
#    compose:
#      lifecycle-management: start_only
#      file: ./compose.yaml
  thymeleaf:
    cache: false
  flyway:
    locations: classpath:db
    enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/videos_online?autoreconnect=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: Root.123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: SpringBootHikariCP
  # rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: pkmer
    password: Root.123456
    listener:
      simple:
        acknowledge-mode: manual # 手动ack
# mybatis 配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:mapper/**/*.xml
  type-handlers-package: org.hzz.*.infrastructure.dao.handler
springdoc:
  use-fqn: true    #  enables fully qualified names


# 用于文档说明
app-version: '@project.version@'
# 自定义的应用配置
app:
  jwt:
    expiration-time: 36000000 # 10h in millisecond
    secret-key: 9cZjXN9uHH0erCgOAdZCsXIAJbeh7Q43eLa/c1a69rU=
  auth:
    ignore-urls:
      - /auth/*
      - /doc/*
      - /v3/*
      - /auth-test/test
      - /auth-test/error
      - /learning-test/*
      - /course-test/*
      - /test/**
      - /error
      - /index
      - /index.html
      - /index.htm
      - /css/*.css
      - /favicon.ico
      - /categorys/**
      - /seasons/**
