package org.hzz.learning.infrastructure.dao.entity;

import java.util.Date;

/**
 * generated by MyBatis Generator.
 * learning_lesson(学生学习课程表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2024/06/24
 */
public class LearningLesson {
    // learning_lesson.id (主键)
    private Long id;

    // learning_lesson.user_id (学员id)
    private Long userId;

    // learning_lesson.course_id (课程id)
    private Long courseId;

    // learning_lesson.status (课程状态，0-未学习，1-学习中，2-已学完，3-已失效)
    private Byte status;

    // learning_lesson.week_freq (每周学习频率，例如每周学习6小节，则频率为6)
    private Byte weekFreq;

    // learning_lesson.plan_status (学习计划状态，0-没有计划，1-计划进行中)
    private Byte planStatus;

    // learning_lesson.learned_sections (已学习小节数量)
    private Integer learnedSections;

    // learning_lesson.latest_section_id (最近一次学习的小节id)
    private Long latestSectionId;

    // learning_lesson.latest_learn_time (最近一次学习的时间)
    private Date latestLearnTime;

    // learning_lesson.create_time (创建时间)
    private Date createTime;

    // learning_lesson.expire_time (过期时间)
    private Date expireTime;

    // learning_lesson.update_time (更新时间)
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getCourseId() {
        return courseId;
    }

    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public Byte getWeekFreq() {
        return weekFreq;
    }

    public void setWeekFreq(Byte weekFreq) {
        this.weekFreq = weekFreq;
    }

    public Byte getPlanStatus() {
        return planStatus;
    }

    public void setPlanStatus(Byte planStatus) {
        this.planStatus = planStatus;
    }

    public Integer getLearnedSections() {
        return learnedSections;
    }

    public void setLearnedSections(Integer learnedSections) {
        this.learnedSections = learnedSections;
    }

    public Long getLatestSectionId() {
        return latestSectionId;
    }

    public void setLatestSectionId(Long latestSectionId) {
        this.latestSectionId = latestSectionId;
    }

    public Date getLatestLearnTime() {
        return latestLearnTime;
    }

    public void setLatestLearnTime(Date latestLearnTime) {
        this.latestLearnTime = latestLearnTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getExpireTime() {
        return expireTime;
    }

    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}