package io.gitee.pkmer.coupon.infrastructure.dao.model.coupon;

import io.gitee.pkmer.mybatis.annotations.SnowflakeId;

/**
 * generated by MyBatis Generator.
 * coupon_scope(优惠券作用范围信息) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2024/08/29
 */
public class CouponScope {
    //
    @SnowflakeId
    private Long id;

    // 范围限定类型：1-分类，2-课程，等等
    private Byte type;

    // 优惠券id
    private Long couponId;

    // 优惠券作用范围的业务id，例如分类id、课程id
    private Long bizId;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Byte getType() {
        return type;
    }

    public void setType(Byte type) {
        this.type = type;
    }

    public Long getCouponId() {
        return couponId;
    }

    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    public Long getBizId() {
        return bizId;
    }

    public void setBizId(Long bizId) {
        this.bizId = bizId;
    }
}