package org.hzz.learning.infrastructure.dao.entity.question;

import java.time.LocalDateTime;

/**
 * generated by MyBatis Generator.
 * interaction_question(互动提问的问题表) 
 * 
 * @author 胖卡
 * @version 1.0.0
 * @date 2024/07/11
 */
public class InteractionQuestion {
    // 主键，互动问题的id
    private Long id;

    // 互动问题的标题
    private String title;

    // 问题描述信息
    private String description;

    // 所属课程id
    private Long courseId;

    // 所属课程章id
    private Long chapterId;

    // 所属课程节id
    private Long sectionId;

    // 提问学员id
    private Long userId;

    // 最新的一个回答的id
    private Long latestAnswerId;

    // 问题下的回答数量
    private Integer answerTimes;

    // 是否匿名，默认false
    private Boolean anonymity;

    // 是否被隐藏，默认false
    private Boolean hidden;

    // 管理端问题状态：0-未查看，1-已查看
    private Byte status;

    // 提问时间
    private LocalDateTime createTime;

    // 更新时间
    private LocalDateTime updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getCourseId() {
        return courseId;
    }

    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    public Long getChapterId() {
        return chapterId;
    }

    public void setChapterId(Long chapterId) {
        this.chapterId = chapterId;
    }

    public Long getSectionId() {
        return sectionId;
    }

    public void setSectionId(Long sectionId) {
        this.sectionId = sectionId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getLatestAnswerId() {
        return latestAnswerId;
    }

    public void setLatestAnswerId(Long latestAnswerId) {
        this.latestAnswerId = latestAnswerId;
    }

    public Integer getAnswerTimes() {
        return answerTimes;
    }

    public void setAnswerTimes(Integer answerTimes) {
        this.answerTimes = answerTimes;
    }

    public Boolean getAnonymity() {
        return anonymity;
    }

    public void setAnonymity(Boolean anonymity) {
        this.anonymity = anonymity;
    }

    public Boolean getHidden() {
        return hidden;
    }

    public void setHidden(Boolean hidden) {
        this.hidden = hidden;
    }

    public Byte getStatus() {
        return status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public LocalDateTime getCreateTime() {
        return createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }
}