services:
  mysql:
    container_name: video_mysql
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - "./docker_data/mysql:/var/lib/mysql"
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Root.123456
      - MYSQL_DATABASE=videos_online
  rabbitmq:
    container_name: video_rabbitmq
    image: rabbitmq:3.13.3-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=pkmer
      - RABBITMQ_DEFAULT_PASS=Root.123456
      - RABBITMQ_PLUGINS_DIR=/opt/rabbitmq/plugins:/usr/lib/rabbitmq/plugins
    volumes:
      - "./docker_data/rabbitmq/data:/var/lib/rabbitmq"
      - "./attachment/rabbitmq/plugins:/usr/lib/rabbitmq/plugins"
      - "./attachment/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:rw"
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    container_name: video_redis
    image: redis:7.2.5
    restart: unless-stopped
    volumes:
      - "./docker_data/redis:/data"
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]